### ISSUE TITLE
Account per world

### ISSUE THREAD

**Issue by SOF3** [SOF3/Capital#10]
As requested by @reyyan987 in https://github.com/poggit-orphanage/EconomyS/issues/76

This should involve creating a schema called "world", with the following config:

```yaml
schema:
  '#type': The type of schema. Possible values are "basic", "currency".
  type: world
  '##': In the world schema, each player has one account for each world.
```

There are several possible configurations, but I am not sure if they are actually useful:

- World groups: Worlds are grouped such that player uses the same account in the worlds in the same group
- World whitelist/blacklist: Player cannot use any accounts at all in these worlds
